---
title: "notebook20190208"
author: "Mark Hagemann"
date: "2/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Working on maps showing errors. Can I get a polyline connecting estimated to true lat/lon?

```{r}
lindata <- valdata %>% 
  dplyr::select(reach_id, node_id, variable:sigma_est) %>% 
  dplyr::filter(variable %in% c("latitude", "longitude")) %>% 
  # dplyr::mutate(pixc_max = pixc_val + 1.96 * sigma_est,
  #               pixc_min = pixc_val - 1.96 * sigma_est) %>% 
  dplyr::select(-pixc_err, -sigma_est) %>% 
  gather(key = "dataset", value = "value", -reach_id:-variable) %>% 
  dplyr::filter(!is.na(value)) %>% 
  spread(key = variable, value = value) %>% 
  st_as_sf(coords = c("longitude", "latitude"))

glimpse(lindata)

lindata_g <- as.data.frame(dplyr::filter(lindata, dataset == "gdem_val"))
lindata_p <- as.data.frame(dplyr::filter(lindata, dataset == "pixc_val"))

lindata2 <- left_join(lindata_g, lindata_p, by = c("reach_id", "node_id"))

```

Just do it in ggplot. 

```{r}
lindata <- valdata %>% 
  dplyr::select(reach_id, node_id, variable:sigma_est) %>% 
  dplyr::filter(variable %in% c("latitude", "longitude")) %>% 
  dplyr::mutate(variable = ifelse(variable == "latitude", "lat", "lon")) %>% 
  gather(key = "dataset", value = "value", -reach_id:-variable) %>% 
  reshape2::dcast(reach_id + node_id ~ variable + dataset) %>% 
  glimpse()

glimpse(lindata)


lin_gg <- ggplot(lindata) + 
  geom_point(aes(x = lon_pixc_val, y = lat_pixc_val)) +
  geom_segment(aes(x = lon_pixc_val, y = lat_pixc_val,
                   xend = lon_gdem_val, yend = lat_gdem_val)) +
  coord_map()

lin_gg
lin_gg + xlim(237.95, 238) + ylim(39.3, 39.4)
```



Tracking down lat/lon errors. How far off are timings between gdem and pixc? Need to modify valdata function. 


```{r}

rt_valdata2 <- function(dir, group = c("nodes", "reaches"),
                       rtname = "rt.nc", gdname = "rt_gdem.nc",
                       keep_na_vars = FALSE,
                       time_round_digits = -2) {
  
  group <- match.arg(group)
  rtdf <- rt_read(paste0(dir, "/", rtname), group = group, 
                  keep_na_vars = keep_na_vars)
  gddf <- rt_read(paste0(dir, "/", gdname), group = group,
                  keep_na_vars = keep_na_vars)
  
  # ID variables for joining rivertile to gdem
  idvars <- c("reach_id", "node_id") #, "time", "time_tai")
  idvars <- intersect(names(rtdf), idvars)
  
  # # time variables need to be rounded.
  # timevars <- intersect(c("time", "time_tai"), names(rtdf))
  # rtdf[timevars] <- round(rtdf[timevars], digits = time_round_digits)
  # gddf[timevars] <- round(gddf[timevars], digits = time_round_digits)  
  
  # variables assumed constant between rivertile and gdem, can be joined 
  # separately. Or, variables only meaningful for actual rivertile data
  commonvars_rch <- c(
    "p_latitud", "p_longitud", "p_n_nodes", "xtrk_dist", "partial_f", 
    "n_good_nod", "obs_frac_n", "reach_q", "geoid_height", "geoid_slop", 
    "solid_tide", "pole_tide", "load_tide", "dry_trop_c", "wet_trp_c", "iono_c",
    "xover_cal_c", "p_n_nodes", "p_dist_out"
  )
  commonvars_nod <- c(
    "area_of_ht", "node_dist", "xtrk_dist", "n_good_pix", "node_q",
    "solid_tide", "pole_tide", "load_tide", "dry_trop_c", "wet_trop_c", 
    "iono_c", "xover_cal_c", "p_dist_out"
  )
  commonvars <- intersect(names(rtdf), c(commonvars_rch, commonvars_nod))
  
  # Vector of variables to compare between rivertile and gdem
  varnames <- c("height", "slope", "width", "area_detct", "area_total",
                "latitude", "longitude", "time")
  # Corresponding uncertainty variables
  uncnames <- setNames(
    c("height_u", "slope_u", "width_u", "area_det_u", "area_tot_u", 
      "latitude_u", "longitud_u", "time"), 
    varnames
  )
  
  varnames <- intersect(names(rtdf), varnames)
  uncnames <- uncnames[varnames]
  
  # Make gathered data.frames
  rtdf_g <- gather(rtdf[c(idvars, varnames)], 
                   key = "variable", value = "pixc_val", -!!idvars)
  gddf_g <- gather(gddf[c(idvars, varnames)], 
                   key = "variable", value = "gdem_val", -!!idvars)
  uncdf_g <- rtdf[c(idvars, uncnames)] %>% 
    setNames(plyr::mapvalues(names(.), from = uncnames, to = varnames)) %>% 
    gather(key = "variable", value = "sigma_est", -!!idvars)
  
  # Join together, including "common" variables
  commondf <- rtdf[c(idvars, commonvars)]
  out <- rtdf_g %>% 
    left_join(gddf_g, by = c(idvars, "variable")) %>% 
    mutate(pixc_err = pixc_val - gdem_val) %>% 
    left_join(uncdf_g, by = c(idvars, "variable")) %>% 
    left_join(commondf, by = idvars)
  out
}
```



```{r}
foo <- rt_valdata2("../output/sac01/", "nodes")

foo %>% filter(variable == "time") %>% 
  ggplot(aes(x = pixc_err)) + geom_histogram()

foo %>% 
  filter(variable %in% c("time", "latitude")) %>% 
  dplyr::select(node_id, variable, pixc_err) %>% 
  reshape2::dcast(node_id ~ variable) %>% 
  # spread(key = variable, value = pixc_err, -reach_id) %>%
  glimpse() %>% 
  plot(time ~ latitude, .)

```

