---
title: "notebook20190425"
author: "Mark Hagemann"
date: "4/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I did most of my work today in yesterday's notebook, building and improving the connectivity algorithm. Now I want to prep figures to go into slides for a couple of presentations tomorrow. 

```{r}
rt_valdata(rodir(14)) %>% 
  rt_val_hist(scale = TRUE, curve = TRUE, vars = c("height", "width"))
  
```

Now showing conditions--what I had before and what I have now. 

Viewing geometry

```{r}
library(ggmap)
allat <- c(passmapdf$latitude, nodemapdf$latitude)
allon <- c(passmapdf$longitude, nodemapdf$longitude)
bbox <- c(min(allon), min(allat), max(allon), max(allat))

bgmap <- get_map(location = bbox, maptype = "terrain")
osmap <- get_map(location = bbox, source = "osm")


ggmap(bgmap)
ggmap(osmap, darken = c(0.5, "white")) +
    # ggplot(aes()) + 
  geom_line(aes(x = longitude, y = latitude,
                group = as.factor(pass),
                linetype = as.factor(pass)),
            data = passmapdf) + 
  geom_point(aes(x = longitude, y = latitude, color = n), 
             data = nodemapdf) +
  scale_color_viridis_c()

```




