---
title: "Approximating a gamma-uniform model"
author: "Mark Hagemann"
date: "7/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I have a sampler and a closed-form approximation for a gamma-uniform model. 

```{r}
data1 <- list(N = 1, y = structure(1.1e-11, .Dim = 1L), mu_l = 2.03e-12, 
              mu_w = 3.14e-11, nlooks = 4)

mod1 <- stan_model("../src/gamma-unif.stan")
samps1 <- sampling(mod1, data = data1, cores = 2)

stan_hist(samps1)
```


Now the approximation.

```{r}
# Need a prior on beta. Beta is gamma, so theta is inverse gamma.
# Prior on theta is inv-gamma(alpha0, beta0)
# Per math, the moments can be matched--iteratively. Here's a function to do so.

ig_mom <- function(nlooks, muw, mul) {
  c <- rep(1, length(muw))
  for (i in 1:15) {
    betai <- 3 * c * (muw + mul)^3 / (2 * nlooks * (muw - mul)^2)
    alphai <- 2 * nlooks * betai / (muw + mul) + 1
    c <- (alphai - 1) / (alphai - 2)
  }
  out <- list(alpha = alphai, beta = betai)
  out
}


# foo <- ig_mom(4, 1e-12, 1e-10)
# mean(1 / rgamma(1000, shape = foo$alpha, rate = foo$beta))
# sd(1 / rgamma(1000, shape = foo$alpha, rate = foo$beta))


theta_postparams <- function(p, nlooks, muw, mul) {
  hypparams <- ig_mom(nlooks = nlooks, muw = muw, mul = mul)
  postshape <- nlooks + hypparams$alpha
  postrate <- hypparams$beta + p
  out <- list(shape = postshape, scale = 1 / postrate)
  out
}

wfrac_postmoms <- function(p, nlooks, muw, mul) {
  postparams <- theta_postparams(p, nlooks, muw, mul)
  postshape <- postparams$shape
  postrate <- 1 / postparams$scale
  thetamean = postrate / (postshape - 1)
  thetavar = postrate^2 / (postshape - 1)^2 / (postshape - 2)

  out <- list(mean = (nlooks * thetamean - mul) / (muw - mul),
              var = nlooks^2 / (muw - mul)^2 * thetavar)
  out$sd <- sqrt(out$var)
  out
}

posts <- with(data1, theta_postparams(p = y, nlooks = nlooks, 
                                      muw = mu_w, mul = mu_l))

theta3 <- 1 / rgamma(1000, shape = posts$shape, scale = posts$scale)
wfrac3 <- with(data1, (theta3 * nlooks - mu_l) / (mu_w - mu_l) )

hist(theta3)
hist(wfrac3)

summary(samps1)$summary[, 1:3]
with(data1, wfrac_postmoms(p = y, nlooks = nlooks, 
                                    muw = mu_w, mul = mu_l))
mean(wfrac3)
sd(wfrac3)
```




