---
title: "River Products Orientation"
author: "Mark Hagemann"
date: "5/20/2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Intro

Session in 3 parts

1. Introduction/refresher on river products
2. Hands-on demonstration of simulated data products
3. Discussion 

## Follow the information


- Data processing flow chart, for orientation *annotated flow chart*
  - Here's where the pixel cloud sits
  - In this brief talk I'll touch on each of these pieces
  - Using specific examples

- Upstream: SLC, PIXC simulator
  - Sacramento River
  - location *Leflet of prior centerlines*
  - *width histogram*--on the smallish side of SWOT-observable rivers
  - Model output as input
    - hydrodyanmic models --> SLC simulator --> pixel cloud generator --> pixel cloud

- Start with Pixel cloud (since we've just covered that)
  - Zoom in to a part of the Sacramento River *index map with box of zoom-in area*
  - *example slant-plane fig*
  - classified, e.g. land, water, etc. *color the image by class*
  - geolocated *same pixels, now in lat/lon*
  - height, area, classification, water fraction, number of looks, etc. 


- Processed through RiverObs *simple black-box diagram*
  - A bit about RiverObs: what it is, where it came from, what it does, where to get it, how to use it
    - requisite shout-outs *GitHub contributors screenshot*
    - where to find it, how to use it
    - What it does, for our purposes
      - inputs are pixel cloud (netcdf), prior database, configuration file
      - outputs are pixcvec (netcdf), river tile vector products (shapefile and netcdf)
    - brief mention of aggregation from pixels to nodes to reaches
      - assignment of pixels to prior nodes *same pixel cloud zoom-in as before, showing node assignments*
      - segment pixels *POSSIBLY add a figure*
      - aggregate pixel values to node values (e.g. height, width, area)
      - aggregate node values to reach values (including slope)
        - ~50 nodes per reach
      - compute additional pixel-scale values --> pixcvec
      - write files
    - it's open-source (unlike much of the rest of the processing chain)
      - You can get it, use it, customize it
      - If you have a pixel cloud, you can produce these outputs right now. 
      - written in Python
  
- Pixel cloud is aggregated to nodes
  - Role of prior database
- Nodes are aggregated to reaches
  - Reach-specific fields
- Splitting into river tiles
- Formats 
  - all as netcdf
  - nodes and reaches as shapefiles
- Example workflow
  - Choose location, time of interest
  - Download tile for a selected pass
  - Work with tile data
  
- Overview of Sacramento River
  - Where's it fit in size distribution?
  - What passes go near it?
  - Where do simulated data (PIXC) come from?
    - hydraulic model


## Hands-on demo

### Objective: understand prior database

- Map of region
  - Use local tiles? TODO
  - a priori database: centerlines, nodes, reaches DONE
  - Click for all info in prior database?
    - This isn't a session on prior database!
  - TEXT
    - h2: Welcome, short overview of UI
    - h2: prior database
    - Where to go next

### Objective: understand passes, tiles

- Map of region
  - paths of satellite for different passes (toggle) DONE
    - Click for pass number DONE
  - outlines of tiles (toggle) TODO
- Timeseries of x-track distance DONE
- Not all passes see all nodes!
- Select a tile, click "Get Data"
  - What should this do?
  - Static image, zoomable via [this method](https://stackoverflow.com/a/26044171) or similar. POSSIBLY
  - TEXT
    - h2: 

### Objective: Understand file structure

- Files tab
  - For each run, put renamed netcdf and shapefiles into an individual folder. DONE
  - Table showing file name and size DONE
  - netcdf structure How to display? TODO
  - shapefile attribute table headers TODO

### Objective: Understand pixel cloud, pixcvec

- Show zoomable static image for pcv POSSIBLY
- Show a single reach's pixels in interactive map DONE
  - Slider to choose which reach is displayed DONE
  - click node for info (height, area, etc.) DONE
  - Legend for classification DONE
- Table of pixel data DONE
  - filter by pixel selection POSSIBLY

### Objective: Understand node product

- Select nodes on map
- Denote nodes not in tile
  - add stroke for in the tile?
- Filter table with node data
  - Toggle for basic, expert columns
 
### Objective: understand reach product

- Show reaches on map DONE
- Show table with all reaches DONE
- Show plots of height, width, slope, area 
- Show regressions of node data TODO

### Objective: understand factors affecting measurement precision



### Objective: think critically about data contained in products

Questions for discussion

- Do any nodes' pixels surprise you? 
- Do the linear fits for nodes --> reaches seem reasonable?
- In what conditions would you be interested in using each tile? 
  - Are some passes better suited for 


## Summary

The following are **sections** of the UI

- header
- map
- table
- file viewer
- plots
- selection
  - tile, "get data"
  - reach (pixc display, node --> reach aggregation)
    - Possibly a range slider? 
  - Map display toggles
    - orbit tracks
    - tile outlines
    - nodes
    - centerlines/reaches
    - pixels (only once data is retrieved)
    
    
## Actions

- Click "get data"
  - bring up file names for this tile

## Required datasets

- orbits
- tiles?
- pixel clouds
- riverobs output



